config/routes.rb
PayWithMe::Application.routes.draw do
  
  resources :funds do
    resources :transactions
  end

   root :to => 'home#index'

   resources :users
   resources :user_sessions

   match 'login' => 'user_sessions#new', :as => :login
   match 'logout' => 'user_sessions#destroy', :as => :logout

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  # GET /transactions
  # GET /transactions.json
  def index
    @fund = Fund.find(params[:fund_id])
    @transactions = @fund.transactions.all.to_a

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @fund = Fund.find(params[:fund_id])
    @transaction = @fund.transactions.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @fund = Fund.find(params[:fund_id])
    @transaction = @fund.transactions.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @fund = Fund.find(params[:fund_id])
    @transaction = @fund.transactions.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @fund = Fund.find(params[:fund_id])
    @user = User.find(params[:user_id])
    @transaction = @transaction.new(params[:transaction])
    @transaction.amount = params[:amount]
    @transaction.user = @user
    @transaction.fund = @fund

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render json: @transaction, status: :created, location: @transaction }
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @fund = Fund.find(params[:fund_id])
    @transaction = @fund.transactions.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @fund = Fund.find(params[:fund_id])
    @transaction = @fund.transactions.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :ok }
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= simple_form_for [@fund, @transaction], :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Transaction</legend>

    <%= f.input :amount %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', transactions_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/transactions/edit.html.erb
<%= render :partial => 'form' %>

app/views/transactions/index.html.erb
<h1>Transactions</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th> type</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.id %></td>
        <td><%= link_to transaction._type, transaction_path(transaction) %></td>
        <td><%= transaction.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_transaction_path(transaction), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', transaction_path(transaction), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_transaction_path, :class => 'btn btn-primary' %>

app/views/transactions/new.html.erb
<%= render :partial => 'form' %>

app/views/transactions/show.html.erb
<h1>Transaction</h1>

<p>
  <b> type</b><br>
  <%= @transaction._type %>
</p>

<p>
  <b></b><br>
  <%= @transaction._id %>
</p>

<p>
  <b>Paid</b><br>
  <%= @transaction.paid %>
</p>

<p>
  <b>Fund</b><br>
  <%= @transaction.fund_id %>
</p>

<p>
  <b>User</b><br>
  <%= @transaction.user_id %>
</p>

<div class="form-actions">
  <%= link_to 'Back', transactions_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_transaction_path(@transaction), :class => 'btn' %>
  <%= link_to 'Delete', transaction_path(@transaction), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>