config/routes.rb
PayWithMe::Application.routes.draw do
  
  resources :funds do
    resources :transactions
  end

   root :to => 'home#index'

   resources :users
   resources :user_sessions

   match 'login' => 'user_sessions#new', :as => :login
   match 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/fund.rb
class Fund
  include Mongoid::Document
  field :description, :type => String
  field :amount, :type => Integer
  field :number_of_people, :type => Float

  has_many :transactions
  belongs_to :user

  validates_presence_of :description
  validates_presence_of :amount

  def single_amount
    (amount / number_of_people).to_s
  end
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController

  # GET /funds
  # GET /funds.json
  def index
    @funds = Fund.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @funds }
    end
  end

  # GET /funds/1
  # GET /funds/1.json
  def show
    @fund = Fund.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fund }
    end
  end

  # GET /funds/new
  # GET /funds/new.json
  def new
    @fund = Fund.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fund }
    end
  end

  # GET /funds/1/edit
  def edit
    @fund = Fund.find(params[:id])
  end

  # POST /funds
  # POST /funds.json
  def create
    @fund = Fund.new(params[:fund])
    @fund.number_of_people = 1.0;

    respond_to do |format|
      if @fund.save
        format.html { redirect_to @fund, notice: 'Fund was successfully created.' }
        format.json { render json: @fund, status: :created, location: @fund }
      else
        format.html { render action: "new" }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /funds/1
  # PUT /funds/1.json
  def update
    @fund = Fund.find(params[:id])

    respond_to do |format|
      if @fund.update_attributes(params[:fund])
        format.html { redirect_to @fund, notice: 'Fund was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funds/1
  # DELETE /funds/1.json
  def destroy
    @fund = Fund.find(params[:id])
    @fund.destroy

    respond_to do |format|
      format.html { redirect_to funds_url }
      format.json { head :ok }
    end
  end
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/views/funds/_form.html.erb
<%= form_for @fund, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Fund</legend>

    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :description, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :amount, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :amount, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', funds_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/funds/edit.html.erb
<%= render :partial => 'form' %>

app/views/funds/index.html.erb
<h1>Funds</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th> type</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @funds.each do |fund| %>
      <tr>
        <td><%= fund.id %></td>
        <td><%= link_to fund._type, fund_path(fund) %></td>
        <td><%= fund.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_fund_path(fund), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', fund_path(fund), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_fund_path, :class => 'btn btn-primary' %>

app/views/funds/new.html.erb
<%= render :partial => 'form' %>

app/views/funds/show.html.erb
<div class="funds-hdr">
  <h1><%= @fund.description %>
    <small> $<%= @fund.amount %></small>
  </h1>
</div>

<%= form_tag users_path, :method => 'get', :id => 'users_search', :class => "form-search" do %>
  <%= text_field_tag :users_search, params[:users_search], :name => "users_search", :class => "input-medium search-query sm-pad" %>
  <%= hidden_field_tag :fund_id, @fund.id %>
  <%= submit_tag "Search", :name => nil %> 
<% end %>

<div id="users-main">
</div>

<div id="trans-main">
</div>

<div class="form-actions">
  <%= link_to 'Back', funds_path, :class => 'btn'  %>
  <%= link_to 'Change Amount', edit_fund_path(@fund), :class => 'btn' %>
  <%= link_to 'Cancel', fund_path(@fund), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>